name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - run: npm ci

      - run: npm test -- --watchAll=false

      - run: npm run build
      
      - name: 📂 Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: melinakrzemowa.pl
          username: deploy@melinakrzemowa.pl
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
