name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # - name: 📂 Deploy files
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: melinakrzemowa.pl
      #     username: deploy@melinakrzemowa.pl
      #     password: ${{ secrets.ftp_password }}
      #     exclude: .git*
      #       - .git*/**
      #       -  **/.git*/**
      #       - node_modules/**
      #       - node_modules/**/*
      #       - .env
